---
title: basketQuery
emoji: ğŸ€
colorFrom: "#f0f0f5"  # Light gray
colorTo: "white"
sdk: gradio
sdk_version: "4.0.0" # Or your Gradio version
app_file: app.py  # Assuming your main file is named app.py
pinned: false
---